# Numpy 개요
- Numerical python
- 고성능 수치 계산을 위한 라이브러리
- 벡터나 행렬 연산에 편리한 기능 제공
- 모든 원소는 같은 자료형만 가능

```
Numeric + Python = Numpy
수학 및 과학 연산을 위한 파이썬 패키지
배열이나 행렬 계산에 용이한 메서드를 제공
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
관련 사이트 : http://www.numpy.org
일반 List에 비해 빠르고, 메모리 효율적

반복문 없이 데이터 배열에 대한 처리를 지원함
선형대수와 관련된 다양한 기능을 제공함
Reference Site
cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS
설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy
```

In [5]:
import numpy as np
np.__version__

'1.26.4'

# 넘파이 배열 모양 이해

## ndim(dimention, rank)
몇차원인지 반환

In [6]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [7]:
a = np.array([2,4,6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [8]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [9]:
a = np.array([[1,2,3],[4,5,6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [11]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

## shape
행렬의 차원, 몇행 몇열인지 반환

In [12]:
a.shape

(2, 2, 3)

In [13]:
a.shape?

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [15]:
a = np.array(3)
a, a.shape # 행렬이 아니니까 shape이 반환 안됨

(array(3), ())

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [19]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [20]:
a.ndim

3

# 넘파이 배열
* 리스트를 넘파이 배열로 생성 np.array(리스트)
* 관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

## 1차원 리스트 객체(이터러블)

In [21]:
myList = [10, 56,88,23,14]
print(myList, type(myList), len(myList))

[10, 56, 88, 23, 14] <class 'list'> 5


In [22]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f"차원={myArr.ndim}, 구조={myArr.shape}, 사이즈={myArr.size}, 길이={len(myArr)}")

[10 56 88 23 14] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), 사이즈=5, 길이=5


## 2차원 리스트 객체(이터러블)

In [23]:
myList2 = [[1,2,3],[4,5,6],[7,8,9]]
myList2, len(myList2)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 3)

In [24]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f"차원={myArr2.ndim}, 구조={myArr2.shape}, 사이즈={myArr2.size}, 길이={len(myArr2)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> 3
차원=2, 구조=(3, 3), 사이즈=9, 길이=3


### 2차원 리스트에서 각 행의 수가 다른 경우?

In [25]:
myList21 = [[1,2,3,4],[5,6,7,8,9],[1,2]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 2]] <class 'list'> 3


In [26]:
myArr21 = np.array(myList21)
#길이가 달라서 넘파이 배열로 만들 수 없음!
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# 넘파이 배열과 리스트의 차이점


* 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
* 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
* 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

## 리스트의 산술연산자

In [27]:
listA = [10,30,50]
listB = [1,2,3]
#리스트 + 리스트 = 조인 역할!
print(listA+listB)
#리스트 + 상수 연산 불가능
print(listA+2)

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [28]:
#리스트의 반복
print(listA*2)
#리스트*리스트 연산 불가
print(listA*listB)

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

## 넘파이의 산술연산자

In [29]:
arrA = np.array([1,2,3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [30]:
arrB = np.array([4,5,6])
print(arrA+arrB)
print(arrA*arrB)
print(arrA/arrB)
print(arrA//arrB) # 몫
print(arrA%arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


# dtype

```
https://numpy.org/doc/stable/reference/arrays.dtypes.html
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다
숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.
```

## 자료형 섞인 경우

In [31]:
#자료형 테스트
myList_c = ['hello', 100, 3.14, True, False]
print(myList_c)

['hello', 100, 3.14, True, False]


In [33]:
myArr_c = np.array(myList_c)
#넘파이 배열은 '문자열'로 자동변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['hello' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [34]:
myArr_d = np.array([100, 3.14, 23.5, 0])
#정수와 실수 혼합시, 더 큰 실수형으로 자동변환
print(myArr_d, type(myArr_d),myArr_d.dtype)

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN

```
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.
```

In [35]:
np.array([0, 1, -1, 0])/np.array([1,0,0,0])

/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_30568/2823503597.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0])/np.array([1,0,0,0])
/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_30568/2823503597.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [36]:
np.log(0)

/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_30568/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [37]:
np.exp(-np.inf)

0.0

# 기술통계

In [38]:
x = np.array([14,2,5,3,6,10,99,123,-231,-23,1,4,0,9,32,1,-6])

In [43]:
#평균
print(x.mean())
print(np.mean(x))

2.8823529411764706
2.8823529411764706


In [44]:
#분산
np.var(x)

4718.103806228373

In [45]:
#표준편차
np.std(x)

68.68845467928634

In [46]:
#최대
np.max(x)

123

In [47]:
#최소
np.min(x)

-231

In [48]:
#중앙값
np.median(x)

4.0

## 사분위수

```
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.
```

In [49]:
#최솟값
np.percentile(x,0)

-231.0

In [51]:
#1사분위수
np.percentile(x,25)

1.0

In [52]:
#2사분위수
np.percentile(x,50)

4.0

In [53]:
#3사분위수
np.percentile(x,75)

10.0

In [54]:
#최대값
np.percentile(x,100)

123.0

# 넘파이 함수로 배열 만들기

```
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소
```

## 1로 초기화

In [55]:
#넘파이 함수로 배열 만들때는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [56]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
#정수 1로 설정해주는 방법
np.ones(10, dtype=int).dtype

dtype('int64')

In [59]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

## 0으로 초기화

In [60]:
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [61]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 리스트+래인지로 선언하는 법

In [63]:
print(list(range(1,21)), type(list(range(1,21))))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [64]:
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20, 2))) # 2씩 증가하게

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [65]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [66]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x10d831b80>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/core/function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value

In [67]:
np.logspace?

Signature:      
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Call signature:  np.logspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function logspace at 0x10d831ca0>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/core/function_base.py
Docstring:      
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.25.0
    Non-scalar 'base` is now supported

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in log-s

In [68]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열


```
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.
```

In [71]:
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [72]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [73]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [74]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [76]:
#arr이 50개여서 안됨~!
arr3 = arr.reshape(4,10)
arr3, arr3.ndim, arr3.shape

ValueError: cannot reshape array of size 50 into shape (4,10)

## 2차원 배열->1차원 배열

In [78]:
arr4 = arr2.flatten()
arr4, arr4.ndim,arr4.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

### Quiz 짝수로 이루어진 배열 만들기

In [80]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [81]:
np.arange(2,101,2).reshape(5,10)

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

### Quiz 2차원인데 1개의 칼럼의 모형을 만들어보자

reshape(-1,n) : 2차원 n개의 칼럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다

In [83]:
arr5 = np.arange(1,31).reshape(-1,1)
arr5, arr5.ndim, arr5.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

### Quiz 5행 4열로 이루어진 모형 만들기

In [85]:
quiz = np.arange(1,21).reshape(5,4)
print(quiz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [86]:
# reshape(-1,n)을 사용해서 5열인 모형으로 만들어보기
quiz.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## shape 심화

In [87]:
np.arange(1, 21).reshape(-1, 7)
#사이즈가 동일해야 reshape가능

ValueError: cannot reshape array of size 20 into shape (7)

In [88]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [89]:
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [90]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [91]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [92]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

# 넘파이 배열의 자료형 형변환

* 배열명2 = 배열명1.astype(자료형)
* 자료형 = np.float64, np.int32

In [93]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [94]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int64'))

In [95]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [96]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [97]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [98]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [99]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [100]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [101]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [102]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [103]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

# 넘파이 배열의 인덱싱

넘파이배열[index]  
넘파이배열[i,j]  
넘파이배열[i][j]  

## 1D array

In [104]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [105]:
a[0], a[4], a[-1]

(1, 9, 9)

In [106]:
a[[0,2,4]]

array([1, 5, 9])

In [107]:
# 행렬구조도 인덱싱이 가능하다.
b = np.array([[1, 3],[4, 2]] )
b

array([[1, 3],
       [4, 2]])

In [108]:
a[b]
# 넘파이 배열1을 넘파이 배열2로 인덱싱하는 경우, 넘파이배열2는 인덱스 번호로 인식

array([[3, 7],
       [9, 5]])

In [109]:
print(a)
a[2] = 0
print(a)

[1 3 5 7 9]
[1 3 0 7 9]


In [110]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [111]:
a[0] += 6
a

array([7, 5, 0, 7, 9])

## 2D array

In [112]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [113]:
# 인덱싱값이 하나일 경우에는 행 인덱싱
a[0], a[1]

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [119]:
# 인덱싱값이 2개 들어가면 행/열 인덱싱
a[0, 0], a[1,3], a[2,4]

(0, 8, 14)

In [120]:
# 값 변경
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [122]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

# 넘파이 배열 슬라이싱

```
1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원
넘파이배열[행, 열] = [start:end:step, start2:end2:step2]
```

## 1D array

In [123]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [124]:
a[:]

array([1, 3, 5, 7, 9])

In [125]:
a[1:]

array([3, 5, 7, 9])

In [126]:
a[-1:]

array([9])

In [127]:
a[1:4]

array([3, 5, 7])

In [128]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
#홀수 뽑기
print(a[1::2])
#짝수 뽑기
print(a[2::2])

[1 3 5 7 9]
[2 4 6 8]


In [130]:
#거꾸로 나열
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2D array

In [131]:
a = np.arange(10,25).reshape(3,5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [132]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
a[:-3]

array([], shape=(0, 5), dtype=int64)

In [134]:
#행의 범위, 열의 범위

a[:,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [135]:
a[:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [136]:
a[:, 4:]

array([[14],
       [19],
       [24]])

In [137]:
a[1:, 2:3]

array([[17],
       [22]])

In [138]:
a[:2, 1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [139]:
a[:-1,1:-1]

array([[11, 12, 13],
       [16, 17, 18]])

In [140]:
a[1,2]

17

In [141]:
a[1][2]

17

In [144]:
print(a)
#행 뒤집기
print(a[::-1])
#열 뒤집기
print(a[:,::-1])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]]
[[14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]


# 전치행렬

In [145]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [146]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [147]:
# reshape과 transpose은 값이 다름을 유의 (reshape는 flatten이 선행)
print(matrix_d.reshape(2,3)) 

[[1 2 3]
 [4 5 6]]


# 난수로 구성된 넘파이 배열

* np.random.randint(start, end, n) : 정수 난수
* np.random.randint(start, end, (i, j))

In [148]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/Users/hanboyoung/Library/Python/3.9/lib/python/site-packages/numpy/random/__init__.py'>
File:        ~/Library/Python/3.9/lib/python/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entr

In [149]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([3, 9, 2, 3, 1, 2, 8, 9, 9, 9])

In [150]:
np.random.randint(1, 49, 6)

array([ 4, 29, 39, 41, 44, 21])

In [151]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[6, 5, 9, 9, 2],
       [9, 3, 8, 1, 8]])

## 섞기

* np.random.shuffle(넘파이배열) 원본에 바로 적용

In [152]:
np.random.shuffle?

Docstring:
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the `~numpy.random.Generator.shuffle`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
random.Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [153]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
np.random.shuffle(matrix_e)
matrix_e

array([ 8,  4,  9,  5,  3, 10,  1,  6,  2,  7])

### Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [157]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

array([ 6, 14, 40, 27, 33, 25])

In [158]:
np.random.randint(1,46,6)

array([41, 24,  4, 37, 23, 34])

## 실수 난수

* np.random.randn(n)
* np.random.randn(i, j)

In [159]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [160]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([-0.60950108, -0.28217799, -0.72429874,  1.4663328 ,  0.28897523,
       -0.29052006, -0.86709935, -1.6472169 , -0.65945547,  0.16516726])

In [161]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-1.18805057, -0.2757179 ,  0.56490922, -1.36124129],
       [ 1.67346864, -0.61351762, -3.00251821,  0.62722963],
       [-0.10784374,  1.93273884, -0.11472849,  0.45848029],
       [-0.7702267 , -0.3750225 ,  0.39337184, -0.38845154]])

In [162]:
matrix1.max(), matrix1.min()

(1.466332804751617, -1.6472169016471172)

In [163]:
np.random.choice?

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the `~numpy.random.Generator.choice`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement. Default is True,
    meaning that a value of ``a`` can be selected multiple times.
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given, the sample assumes a unif

# 집계함수에서의 축

* 2차원에서의 집계합수(sum, mean)
* axis = 0, 1
* np.sum(넘파이배열, axis=0/1)
* np.mean(넘파이배열, axis=0/1)
* np.sort(넘파이배열, axis=0/1)

In [164]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[ 3, 37,  9, 37, 13],
       [ 5, 19, 42, 22, 37],
       [14, 34, 17, 37, 29],
       [12, 37, 22, 21, 35],
       [28, 33,  2, 12, 37]])

In [165]:
m1[0,::]

array([ 3, 37,  9, 37, 13])

In [166]:
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x10d7e2820>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/core/fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which

### Quiz

In [167]:
#1번째 행의 합계는?
m1[0,:]

array([ 3, 37,  9, 37, 13])

In [168]:
np.sum(m1[0,:], axis=0)

99

In [169]:
#3번째 열의 합계는
np.sum(m1[:,2], axis = 0)

92

## np.sort()

In [170]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[19, 22, 28],
       [11, 44, 10],
       [23,  7, 37],
       [45, 43, 15]])

In [171]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x10d7dc820>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str

In [172]:
np.sort(m2) # 행안에서 열정렬 # default axis = -1 마지막 축을 따라 정렬

array([[19, 22, 28],
       [10, 11, 44],
       [ 7, 23, 37],
       [15, 43, 45]])

In [173]:
m2

array([[19, 22, 28],
       [11, 44, 10],
       [23,  7, 37],
       [45, 43, 15]])

In [174]:
np.sort(m2, axis=0) # 열정렬(행방향) 오름차순(요소별로)

array([[11,  7, 10],
       [19, 22, 15],
       [23, 43, 28],
       [45, 44, 37]])

In [175]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다(sort는 +요소별 정렬까지 해줌)

array([[45, 43, 15],
       [23,  7, 37],
       [11, 44, 10],
       [19, 22, 28]])

In [176]:
m2

array([[19, 22, 28],
       [11, 44, 10],
       [23,  7, 37],
       [45, 43, 15]])

In [177]:
np.sort(m2, axis=1) # 행정렬(열방향 오름차순)

array([[19, 22, 28],
       [10, 11, 44],
       [ 7, 23, 37],
       [15, 43, 45]])

In [178]:
m2[::-1, ::-1] 

array([[15, 43, 45],
       [37,  7, 23],
       [10, 44, 11],
       [28, 22, 19]])

## 인덱스 소팅

np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [179]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0])

In [180]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

# 넘파이 배열의 요소 추가와 삭제

## 삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)  
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력

In [181]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
np.insert?

Signature:       np.insert(arr, obj, values, axis=None)
Call signature:  np.insert(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function insert at 0x10d99a820>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/lib/function_base.py
Docstring:      
Insert values along the given axis before the given indices.

Parameters
----------
arr : array_like
    Input array.
obj : int, slice or sequence of ints
    Object that defines the index or indices before which `values` is
    inserted.

    .. versionadded:: 1.8.0

    Support for multiple insertions when `obj` is a single scalar or a
    sequence with one element (similar to calling insert multiple
    times).
values : array_like
    Values to insert into `arr`. If the type of `values` is different
    from that of `arr`, `values` is converted to the type of `arr`.
    `values` should be shaped so that ``arr[...,obj,...] = values``
    is legal.
axis : int, optional
    Axis along which t

In [183]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [184]:
m3[0]

1

In [185]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [186]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [187]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [189]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [190]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [191]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [192]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [193]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [194]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 삭제

np.delete(배열명, 위치인덱스, axis=0/1)

In [195]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

# 배열 합치기

* np.vstack((배열1,배열2....)) : 세로 합치기
* np.hstack((배열1,배열2....)) : 가로 합치기
* np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

## 1차원 배열 합치기

- vstack
- hstack

In [196]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [197]:
np.hstack((a,b)), np.hstack((a,b)).ndim, np.hstack((a,b)).shape

(array([1, 2, 3, 4, 5, 6]), 1, (6,))

## 2차원 배열 합치기

In [198]:
c = np.array( [[1,2,3]] ) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [199]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [200]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [201]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask

* 조건절의 결과는 True, False로 반환
* True인 결과의 데이터 반환
* 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~


In [202]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [203]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [204]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [205]:
len(matrix[matrix > 10])

10

In [206]:
np.sum(matrix > 10)

10

# Quiz : 1~100 사이 난수 30개를 추출하여 넘파이 배열 생성, 30보다 크거나 70보다 작은 수 출력

In [210]:
num = np.random.randint(1,101,30)
print(num)
print((num>30)&(num<70))

print(num[(num>30)&(num<70)])

[58 27 17 89 99 22 75 93 63 98 60 62 64 50 12 45 85 81 13 73 23 37 67 49
 50 96 26 41 32 10]
[ True False False False False False False False  True False  True  True
  True  True False  True False False False False False  True  True  True
  True False False  True  True False]
[58 63 60 62 64 50 45 37 67 49 50 41 32]


In [211]:
# ~은 revere를 의미
num[~(num > 30) & (num < 70)]

array([27, 17, 22, 12, 13, 23, 26, 10])

## 10보다 작거나 90보다 큰 수 출력

In [212]:
num[(num<10)| (num>90)]

array([99, 93, 98, 96])

# fancy indexing(filtering)

넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.
  
넘파이배열1[넘파이배열2]  
넘파이배열2 : 인덱스 역할 (only 정수형)

In [213]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([35, 51, 22, 75, 65, 32, 49, 53, 51, 36, 18, 50, 49, 29, 47, 97, 84,
        42, 83, 31, 62, 71, 12, 41,  4, 60, 47, 21, 58,  4]),
 array([35, 22, 75, 18, 62]))

# np.where()을 이용한 필터링

* np.where(조건식) : 조건식 만족하는 인덱스 반환
* np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
* 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [214]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [215]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [216]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4]),))