# 0911 Numpy

- numerical python
- 고성능 수치 계산을 위한 라이브러리
- 벡터나 행렬 연산에 편리한 기능 제공
- 모든 원소는 같은 자료형만 가능

In [1]:
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)

<class 'numpy.ndarray'>
(3, 5)
15
int64


In [4]:
b = [-1, 2, 5, -3, 0, -7, -9, 1, -4, 7]
print(type(b))

<class 'list'>


In [5]:
b = np.array(b)
print(type(b))

<class 'numpy.ndarray'>


In [6]:
t = (10,20,30,40,50)
print(type(t))

<class 'tuple'>


In [7]:
t = np.array(t)
print(type(t))

<class 'numpy.ndarray'>


In [8]:
s = {10, 20, 30, 40, 50}
print(type(s))

<class 'set'>


In [9]:
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>


In [10]:
print(b.shape)
print(b.ndim)
print(b.dtype)

(10,)
1
int64


In [11]:
print(b)

[-1  2  5 -3  0 -7 -9  1 -4  7]


In [12]:
print(np.abs(b))

[1 2 5 3 0 7 9 1 4 7]


In [13]:
print(np.sqrt(b))

[       nan 1.41421356 2.23606798        nan 0.                nan
        nan 1.                nan 2.64575131]


/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_66881/1940396832.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(b))


In [14]:
print(np.square(b))

[ 1  4 25  9  0 49 81  1 16 49]


In [15]:
print(np.isnan(b))

[False False False False False False False False False False]


In [16]:
print(np.sum(b))

-9


In [17]:
print(np.mean(b))

-0.9


In [18]:
print(np.max(b))
print(np.min(b))

7
-9


In [19]:
# 최대/최소 값의 인덱스
print(np.argmax(b))
print(np.argmin(b))

9
6


In [20]:
print(np.sort(b)) # ASC
print(np.sort(b)[::-1]) # DSC
print(-np.sort(-b)) # DSC

[-9 -7 -4 -3 -1  0  1  2  5  7]
[ 7  5  2  1  0 -1 -3 -4 -7 -9]
[ 7  5  2  1  0 -1 -3 -4 -7 -9]


In [21]:
print(np.median(b))

-0.5


In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
d = np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
np.zeros_like(d)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.random.rand(3,3)

array([[0.86976628, 0.8435109 , 0.10956951],
       [0.19671491, 0.97052531, 0.80553112],
       [0.07486585, 0.0362639 , 0.05907254]])

In [26]:
np.random.randint(1,40,(3,3,3))

array([[[ 2, 11, 39],
        [ 2, 22, 27],
        [27, 34, 20]],

       [[ 7,  9,  9],
        [31,  7, 34],
        [33, 12,  4]],

       [[ 6, 16,  3],
        [16, 33, 16],
        [27, 15, 10]]])

# 0912 Numpy

## numpy array의 계산

In [31]:
import numpy as np

In [44]:
c = [[1,2,3],[41,51, 61]]
print(type(c))

<class 'list'>


In [45]:
c = np.array(c)
print(type(c))

<class 'numpy.ndarray'>


### axis = 0 : 행 계산, axis = 1 : 열계산
[행열계산 설명](https://velog.io/@jhdai_ly/%EB%84%98%ED%8C%8C%EC%9D%B4Numpy-%ED%8C%90%EB%8B%A4%EC%8A%A4Pandasaxis%EC%9D%98-%EC%9D%98%EB%AF%B8-%ED%96%89%EC%B6%95row%EA%B3%BC-%EC%97%B4column%EC%B6%95-axis0-axis1)

In [47]:
print("행계산", np.sum(c, axis=0))
print("열계산",np.sum(c, axis=1))
print("전체",np.sum(c))

행계산 [42 53 64]
열계산 [  6 153]
전체 159


In [40]:
print(np.median(c, axis=0))
print(np.median(c, axis=1))
print(np.median(c))

[2.5 3.5 4.5]
[2. 5.]
3.5


In [42]:
print(np.mean(c, axis=0))
print(np.mean(c, axis=1))
print(np.mean(c))

[2.5 3.5 4.5]
[2. 5.]
3.5


In [43]:
print(np.max(c))
print(np.max(c, axis=0))
print(np.max(c, axis=1))

6
[4 5 6]
[3 6]


In [ ]:
print(np.std(c))
print(np.var(c))

### element wise 계산

In [49]:
d = np.array([10,20,30,40,50])
print(d+2)
e = np.array([1,2,3,4,5])
print(d+2)

[12 22 32 42 52]
[12 22 32 42 52]


In [50]:
print(d**2)

[ 100  400  900 1600 2500]


In [52]:
print(np.sin(d)) # sin 값

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [53]:
print(d>35)

[False False False  True  True]


#### numpy array의 사칙연산 방법

In [56]:
print(np.add(d,e))
print(np.subtract(d,e))
print(np.multiply(d,e))
print(np.divide(d,e))

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [57]:
print(d+e)
print(d-e)
print(d*e)
print(d/e)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [62]:
f = np.array([[0,1], [1,1]])
g = np.array([[2,0], [3,4]])

print( f*g )
print( f@g ) # 행렬곱
print(np.dot(f,g)) # 행렬곱


[[0 0]
 [3 4]]
[[3 4]
 [5 4]]


In [64]:
h = np.zeros(10)
print(h)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [65]:
i = np.zeros((5,5))
print(i)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [66]:
j = np.ones(10)
print(j)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## np.random

- np.random.random : 0~1 사이 난수 발생
- np.random.randint : 균일 분포의 정수 난수 발생
- np.random.rand : 0~1 사이 균일 분포의 난수 matrix array 생생
- np.random.randn : 가우시안 표준 정규분포 난수, matrix array 생성
- np.random.normal : 평균, 표준편차, sample 개수 지정해서 생성

In [69]:
k = np.random.random(10)*100
kk = np.array([int(i)for i in k])
print(type(k))
print(type(kk))
print(k)
print(kk)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[32.18130119  4.59804826 67.75687664 78.16065937  4.68168709  8.30222685
 21.33385987 41.35056946 50.6814818   3.45051659]
[32  4 67 78  4  8 21 41 50  3]


In [71]:
print(np.random.randint(10,20))
print(np.random.rand(5,2))

19
[[0.92098147 0.14136318]
 [0.15156496 0.28966295]
 [0.37919565 0.94742041]
 [0.40594572 0.05984849]
 [0.43954946 0.27578731]]


#### 슬라이싱

In [72]:
#list
m = [i for i in range(10,20)]
print(m[:5])
print(m[:5:2])
print(m[:])
print(m[5:])
print(m[:-1])
print(m[::-1])

[10, 11, 12, 13, 14]
[10, 12, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


In [102]:
w = np.arange( 10, 20 )
print( w[0:5] )
print( w[0:5:2] )
print( w[:-2] )

[10 11 12 13 14]
[10 12 14]
[10 11 12 13 14 15 16 17]


In [75]:
r = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
print(r[2][2])
print(r[:][:])
print(r[2][:])
print(r[1][:2])

13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[6, 7]


In [76]:
print(r[:2][:2])
#1,2, /6,7만 나오는거 아냐? 아님!
#r[:2]를 계산하면 0,1 행이 나온다
#거기서 또 0,1의 행을 뽑으라고 하는것임!! 결국 전체가 나옴
# 결국 (r[:2])[:2] 인것!

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [78]:
# np.array
s = np.arange(1,16).reshape(3,5)
print(s)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [79]:
print(s[2][2])
print(s[:][:])
print(s[2][:])
print(s[1][:2])

13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[6 7]


In [81]:
print(s[:2][:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [82]:
print(s[:2,:2])
#위에서 내가 원했던 부분 행렬만 뽑을 수 있음!!!!!

[[1 2]
 [6 7]]


In [83]:
print(s[::-1,::-1])

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [84]:
print(s[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [85]:
print(s[:-1,:-1])

[[1 2 3 4]
 [6 7 8 9]]


In [87]:
print(s[2,2])

13


In [88]:
print(s[[0,2]])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [89]:
print(s[:,[1,3,4]])

[[ 2  4  5]
 [ 7  9 10]
 [12 14 15]]


In [94]:
print(s[[0,2],[3,4]])
# 0행의 3열, 2행의 4열을 뽑아줌

[ 4 15]


In [97]:
print(s)
print(s.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## numpy 데이터의 결합/분리

In [101]:
a = [1, 2, 3]
b = [4, 5, 6]
c = zip(a,b)
for i in c:
    print(i)

(1, 4)
(2, 5)
(3, 6)


In [105]:
c = np.floor(np.random.rand(2,2)*100)
print(c)
d = np.floor(np.random.rand(2,2)*100)
print(d)

[[39. 76.]
 [88. 88.]]
[[66.  5.]
 [ 0. 62.]]


In [111]:
# 각 요소들을 더해버림!
print(c+d)

# np.array를 합쳐주려면 hstack, vstack 사용
print(np.hstack((c,d)))
print(np.vstack((c,d)))
print(c+2)

[[105.  81.]
 [ 88. 150.]]
[[39. 76. 66.  5.]
 [88. 88.  0. 62.]]
[[39. 76.]
 [88. 88.]
 [66.  5.]
 [ 0. 62.]]
[[41. 78.]
 [90. 90.]]


In [113]:
e = np.floor(np.random.rand(2,15)*100)
print(e)

[[51. 56. 26. 96. 98. 66. 12.  7. 36. 62. 87. 28. 54. 11. 41.]
 [65. 35. 24.  5. 13. 24. 94. 57. 64. 31. 35. 50. 29. 59. 48.]]


In [116]:
a = np.hsplit(e,3) # e를 3개로 잘라라
for arr in a:
    print(arr)

[[51. 56. 26. 96. 98.]
 [65. 35. 24.  5. 13.]]
[[66. 12.  7. 36. 62.]
 [24. 94. 57. 64. 31.]]
[[87. 28. 54. 11. 41.]
 [35. 50. 29. 59. 48.]]


In [117]:
b = np.hsplit(e, (3,7)) # e를 [:3][3:7][7:]로 잘라라
for arr in b:
    print(arr)

[[51. 56. 26.]
 [65. 35. 24.]]
[[96. 98. 66. 12.]
 [ 5. 13. 24. 94.]]
[[ 7. 36. 62. 87. 28. 54. 11. 41.]
 [57. 64. 31. 35. 50. 29. 59. 48.]]


In [118]:
c = np.hsplit(e, (3,7,12)) # e를 [:3][3:7][7:12][12:로 잘라라
for arr in c:
    print(arr)

[[51. 56. 26.]
 [65. 35. 24.]]
[[96. 98. 66. 12.]
 [ 5. 13. 24. 94.]]
[[ 7. 36. 62. 87. 28.]
 [57. 64. 31. 35. 50.]]
[[54. 11. 41.]
 [29. 59. 48.]]


### 삼함연산

In [123]:
f = np.array([1,2,3,4,5])
g = np.array(['a','b','c','d','e'])
h = np.array([True, False, False, True, True])

In [124]:
for x,y,z in zip(f,g,h):
    print(x, y, z)

1 a True
2 b False
3 c False
4 d True
5 e True


In [126]:
print([x if z else y for x, y, z in zip(f, g, h)])
# z가 거짓이면 y, 참이면 x를 출력하라!

[1, 'b', 'c', 4, 5]


In [127]:
print(np.where(h, f, g)) #삼함연산을 쉽게 해줌!
# h의 값 TF에 따라서 T면 f, F면 g

['1' 'b' 'c' '4' '5']


In [128]:
print(np.where(f < 3, "3보다 작다", "3보다 크다"))

['3보다 작다' '3보다 작다' '3보다 크다' '3보다 크다' '3보다 크다']


In [129]:
print(np.where(h, "True", "False"))

['True' 'False' 'False' 'True' 'True']


In [130]:
i = np.arange(10)
np.save('i.npy',i)
ii = np.load('i.npy')
print(ii)

[0 1 2 3 4 5 6 7 8 9]


In [133]:
j - np.arange(10)
k = np.arange(10)
np.savez('jk.npz', x = j, y = k)
jk = np.load('jk.npz')
print(type(jk))
print(jk['x'])
print(jk['y'])

<class 'numpy.lib.npyio.NpzFile'>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
