# Numpy

- numerical python
- 고성능 수치 계산을 위한 라이브러리
- 벡터나 행렬 연산에 편리한 기능 제공
- 모든 원소는 같은 자료형만 가능

In [1]:
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)

<class 'numpy.ndarray'>
(3, 5)
15
int64


In [4]:
b = [-1, 2, 5, -3, 0, -7, -9, 1, -4, 7]
print(type(b))

<class 'list'>


In [5]:
b = np.array(b)
print(type(b))

<class 'numpy.ndarray'>


In [42]:
t = (10,20,30,40,50)
print(type(t))

<class 'tuple'>


In [43]:
t = np.array(t)
print(type(t))

<class 'numpy.ndarray'>


In [44]:
s = {10, 20, 30, 40, 50}
print(type(s))

<class 'set'>


In [45]:
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>


In [46]:
print(b.shape)
print(b.ndim)
print(b.dtype)

(10,)
1
int64


In [47]:
print(b)

[-1  2  5 -3  0 -7 -9  1 -4  7]


In [48]:
print(np.abs(b))

[1 2 5 3 0 7 9 1 4 7]


In [49]:
print(np.sqrt(b))

[       nan 1.41421356 2.23606798        nan 0.                nan
        nan 1.                nan 2.64575131]


/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_49268/1940396832.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(b))


In [50]:
print(np.square(b))

[ 1  4 25  9  0 49 81  1 16 49]


In [51]:
print(np.isnan(b))

[False False False False False False False False False False]


In [52]:
print(np.sum(b))

-9


In [53]:
print(np.mean(b))

-0.9


In [55]:
print(np.max(b))
print(np.min(b))

7
-9


In [56]:
# 최대/최소 값의 인덱스
print(np.argmax(b))
print(np.argmin(b))

9
6


In [6]:
print(np.sort(b)) # ASC
print(np.sort(b)[::-1]) # DSC
print(-np.sort(-b)) # DSC

[-9 -7 -4 -3 -1  0  1  2  5  7]
[ 7  5  2  1  0 -1 -3 -4 -7 -9]
[ 7  5  2  1  0 -1 -3 -4 -7 -9]


In [7]:
print(np.median(b))

-0.5


In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
d = np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
np.zeros_like(d)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.random.rand(3,3)

array([[0.88894414, 0.37029896, 0.34281305],
       [0.1036998 , 0.72718498, 0.01364175],
       [0.04331346, 0.6569603 , 0.96598733]])

In [8]:
np.random.randint(1,40,(3,3,3))

array([[[19, 32,  6],
        [ 1, 17, 21],
        [ 9, 22, 15]],

       [[33, 15, 16],
        [21,  8, 19],
        [38, 12, 25]],

       [[32, 31, 22],
        [15,  2, 38],
        [ 8, 37, 32]]])