# Pandas

In [3]:
import pandas as pd
import numpy as np

## Series with list

In [8]:
s = pd.Series([1,2,3,4,5,6,7,8,9])
print(type(s))
print(s.index)
print(s.dtype)
print(s)
s.index = ['a', 'b', 'c', 'd','e','f','g','h','i'] # 원하는 인덱스 설정
print(s)

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=9, step=1)
int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64


In [14]:
ss = pd.Series([1,2,3,4,5,6,7,8,9],['a', 'b', 'c', 'd','e','f','g','h','i'])
print(s)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64


In [15]:
print(ss.index)
print(ss.values)
print(ss[0])
print(ss['a'])

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')
[1 2 3 4 5 6 7 8 9]
1
1


/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_76379/1386725536.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ss[0])


In [13]:
print(ss[0:5])
print(ss['a':'d'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


## Series with dictionary

In [16]:
d = {'a': 10, 'd': 20, 'f': 30, 'h':40}
print(type(d))

<class 'dict'>


In [17]:
#순서대로 반복문 돌리고 싶을 때
#items() = (key,value) 튜플로 값을 내어 줌
for key, value in d.items():
    print(key, value)

a 10
d 20
f 30
h 40


In [18]:
print(d['a'])

10


In [19]:
print(d.a) # 이렇게는 안됨, 시리즈처럼 값 뽑기,,

AttributeError: 'dict' object has no attribute 'a'

In [21]:
s = pd.Series(d)
print(s)

a    10
d    20
f    30
h    40
dtype: int64


In [23]:
print(s.index)
print(s.values)
print(s['a'])
print(s.a)

Index(['a', 'd', 'f', 'h'], dtype='object')
[10 20 30 40]
10
10


## Dictionary to Dataframe

In [24]:
d = {
    "name" : ['kim','lee','park','jung'],
    "age" : [25, 30, 35, 20],
    'tel' : ['1111-2222','2222-3333','3333-4444','4444-5555']
}
print(type(d))

<class 'dict'>


In [25]:
df = pd.DataFrame(d)
print(df)

   name  age        tel
0   kim   25  1111-2222
1   lee   30  2222-3333
2  park   35  3333-4444
3  jung   20  4444-5555


In [27]:
print(df.index)
print(df.columns)
print(df.values)

RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'tel'], dtype='object')
[['kim' 25 '1111-2222']
 ['lee' 30 '2222-3333']
 ['park' 35 '3333-4444']
 ['jung' 20 '4444-5555']]


In [28]:
df.index.name = 'Num'
df.columns.nave = 'User'
print(df)

     name  age        tel
Num                      
0     kim   25  1111-2222
1     lee   30  2222-3333
2    park   35  3333-4444
3    jung   20  4444-5555


In [29]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1, name='Num')
Index(['name', 'age', 'tel'], dtype='object')


## Numpy to Dataframe

In [30]:
n = np.array(
    [
        ['kim', 20, '1111-2222'],
        ['lee', 20, '2222-3333'],
        ['park', 35, '3333-4444'],
        ['jung', 25, '4444-5555']
    ]
)
print(type(n))

<class 'numpy.ndarray'>


In [31]:
df = pd.DataFrame(n)
df.columns = ['name', 'age', 'tel']
df.index = ['a', 'b', 'c', 'd']
print(df)

   name age        tel
a   kim  20  1111-2222
b   lee  20  2222-3333
c  park  35  3333-4444
d  jung  25  4444-5555


In [32]:
print(df.index)
print(df.columns)

Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['name', 'age', 'tel'], dtype='object')


In [33]:
df = pd.DataFrame(n, columns=['name', 'age', 'tel'], index=['a', 'b', 'c', 'd'])
print(df)

   name age        tel
a   kim  20  1111-2222
b   lee  20  2222-3333
c  park  35  3333-4444
d  jung  25  4444-5555


In [34]:
print(df.describe())

       name age        tel
count     4   4          4
unique    4   3          4
top     kim  20  1111-2222
freq      1   2          1


In [37]:
print( df['name'] )

a     kim
b     lee
c    park
d    jung
Name: name, dtype: object


In [38]:
print( df[['name','tel']] )

   name        tel
a   kim  1111-2222
b   lee  2222-3333
c  park  3333-4444
d  jung  4444-5555


In [39]:
print( df['name'][2] )

park


/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_76379/432014822.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print( df['name'][2] )


In [45]:
print( df['name']['c'] )
print( df['name'].c )

park
park


In [46]:
print( df['name']['b':'d'] )

b     lee
c    park
d    jung
Name: name, dtype: object


In [48]:
print( df.name, df.age )

a     kim
b     lee
c    park
d    jung
Name: name, dtype: object a    20
b    20
c    35
d    25
Name: age, dtype: object
park


In [49]:
print( df.name.c )

park


In [50]:
print( df[:][:] )

   name age        tel
a   kim  20  1111-2222
b   lee  20  2222-3333
c  park  35  3333-4444
d  jung  25  4444-5555


In [51]:
print( df[:2][:1] )

  name age        tel
a  kim  20  1111-2222


In [52]:
print( df[['name','tel']] )

   name        tel
a   kim  1111-2222
b   lee  2222-3333
c  park  3333-4444
d  jung  4444-5555


In [53]:
# print( df[[ 0, 2 ]] )              # 에러    컬럼명이 있는 경우 숫자 X
# print( df[0][0] )                  # 에러

In [54]:
df[ 'address' ] = [ '서울', '수원', '인천', '안산' ]
df[ 'age' ][ 'A' ] = 30
df[ 'adult' ] = df[ 'age' ].astype( np.int64 ) > 30

print(df)

   name age        tel address  adult
a   kim  20  1111-2222      서울  False
b   lee  20  2222-3333      수원  False
c  park  35  3333-4444      인천   True
d  jung  25  4444-5555      안산  False


/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_76379/1488260088.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[ 'age' ][ 'A' ] = 30


In [55]:
del( df[ 'adult' ] )
print( df )

   name age        tel address
a   kim  20  1111-2222      서울
b   lee  20  2222-3333      수원
c  park  35  3333-4444      인천
d  jung  25  4444-5555      안산


# Pandas 정렬

## Series 정렬

In [56]:
s = pd.Series( [ 10, 40, 50, 20, 70, 60 ], index=[ 'a', 'd', 'f', 'g', 'b', 'c' ] )
print(s)
s = s.sort_index( ascending=False )
print( s )

a    10
d    40
f    50
g    20
b    70
c    60
dtype: int64
g    20
f    50
d    40
c    60
b    70
a    10
dtype: int64


In [57]:
s = s.sort_values()
print( s )

a    10
g    20
d    40
f    50
c    60
b    70
dtype: int64


## DataFrame 정렬

In [69]:
df = pd.DataFrame( [[ 4, 5, 40, 100 ],
                    [ 300, 10, 200, 2],
                    [ 20, 400, 4, 30 ]], index=[ 'c', 'a', 'b' ], columns=[ 'D', 'C', 'A', 'B' ])
print( df )

     D    C    A    B
c    4    5   40  100
a  300   10  200    2
b   20  400    4   30


In [64]:
# index 기준 정렬
df = df.sort_index()
print(df)
df = df.sort_index( axis=0 )
print(df)

     D    C    A    B
a  300   10  200    2
b   20  400    4   30
c    4    5   40  100
     D    C    A    B
a  300   10  200    2
b   20  400    4   30
c    4    5   40  100


In [65]:
#column기준 정렬
df = df.sort_index( axis=1, ascending=False )
print(df)

     D    C    B    A
a  300   10    2  200
b   20  400   30    4
c    4    5  100   40


In [70]:
# 행끼리 정렬, DESC
df = df.sort_values( by='A', ascending=False )
print(df)
# A컬럼의 index a가 200으로 가장 크고 b가 4로 가장 작아서, 그 기준으로 전체 row가 정렬됨

     D    C    A    B
a  300   10  200    2
c    4    5   40  100
b   20  400    4   30


In [71]:
# 행이 2개인 경우, ASC
df = df.sort_values( by=['A', 'B'] )
print(df)
# A컬럼의 index a가 200으로 가장 크고 b가 4로 가장 작아서, 그 기준으로 전체 row가 정렬됨
# 만약 A컬럼에 동일한 값이 있었다면, 다음으로는 B 기준

     D    C    A    B
b   20  400    4   30
c    4    5   40  100
a  300   10  200    2


# 슬라이싱
- .iloc : 정수 인덱스
- .loc : 라벨 인덱스
- .ix : deprecated

## list

In [72]:
m = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
print( m )

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [73]:
print( m[2][2] )
print( m[:][:] )
print( m[:2][:2] )

9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6]]


# numpy

In [74]:
n = np.array( m )
print( n )

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
print( n[2][2] )
print( n[:][:] )
print( n[:2][:2] )
print( n[:2, :2] )

9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


## Pandas

In [76]:
df = pd.DataFrame( n )
print( df )

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [77]:
print( df[2][2] )
print( df[:][:] )
print( df[:2][:2] )

9
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   0  1  2
0  1  2  3
1  4  5  6


## iloc

In [78]:
df = pd.DataFrame( np.arange( 1, 21 ).reshape( 5, 4 ), columns=['A', 'B', 'C', 'D'] )
print( df )

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [79]:
print( df['C'][2] )
print( df[['A', 'D']] )

11
    A   D
0   1   4
1   5   8
2   9  12
3  13  16
4  17  20


In [80]:
print( df.iloc[2][2] )
print( df.iloc[2, 2] )

11
11


/var/folders/5n/kjkw6sh12dx20bbd340zn1pr0000gn/T/ipykernel_76379/2665944372.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print( df.iloc[2][2] )


In [81]:
print( df.iloc[:2, :2] )

   A  B
0  1  2
1  5  6


In [82]:
print( df.iloc[:3:2, :3:2] )

   A   C
0  1   3
2  9  11


In [83]:
print( df.iloc[:2, :-1] )

   A  B  C
0  1  2  3
1  5  6  7


In [84]:
print( df.iloc[::-1, ::-1] )

    D   C   B   A
4  20  19  18  17
3  16  15  14  13
2  12  11  10   9
1   8   7   6   5
0   4   3   2   1


## loc

In [85]:
print( df )
print( df.loc[2, 'C'] )

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
11


In [88]:
print( df.loc[:2, :'C'] )

   A   B   C
0  1   2   3
1  5   6   7
2  9  10  11


In [89]:
print( df[:2] )

   A  B  C  D
0  1  2  3  4
1  5  6  7  8


In [90]:
print( df.loc[1:3, 'B':'D'] )

    B   C   D
1   6   7   8
2  10  11  12
3  14  15  16


In [91]:
print( df.loc[:, 'C'] )

0     3
1     7
2    11
3    15
4    19
Name: C, dtype: int64


In [92]:
print( df.loc[:, ['B', 'D']] )

    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20


In [93]:
print( df[['B' ,'D']] )

    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20


## drop

In [105]:
df = pd.DataFrame( np.arange( 1, 21 ).reshape( 5, 4 ), columns=['A', 'B', 'C', 'D'] )
print(df)
df['E'] = [ 31, 32, 33, 34, 35 ]
print(df)

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
    A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4  17  18  19  20  35


In [106]:
df.loc[5] = [ 90, 91, 92, 93, 94 ]
print(df)

    A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4  17  18  19  20  35
5  90  91  92  93  94


In [107]:
df.loc[:, 'F'] = [ 40, 41, 42, 43, 44, 45 ] 
print(df)

    A   B   C   D   E   F
0   1   2   3   4  31  40
1   5   6   7   8  32  41
2   9  10  11  12  33  42
3  13  14  15  16  34  43
4  17  18  19  20  35  44
5  90  91  92  93  94  45


In [108]:
df.loc[0, 'A'] = 99
print(df)

    A   B   C   D   E   F
0  99   2   3   4  31  40
1   5   6   7   8  32  41
2   9  10  11  12  33  42
3  13  14  15  16  34  43
4  17  18  19  20  35  44
5  90  91  92  93  94  45


In [109]:
df.loc[1, 'A':'C'] = [100, 101, 102]
print( df )

     A    B    C   D   E   F
0   99    2    3   4  31  40
1  100  101  102   8  32  41
2    9   10   11  12  33  42
3   13   14   15  16  34  43
4   17   18   19  20  35  44
5   90   91   92  93  94  45


In [110]:
df.loc[3, ['A', 'C', 'E']] = [200, 201, 202]
print(df)

     A    B    C   D    E   F
0   99    2    3   4   31  40
1  100  101  102   8   32  41
2    9   10   11  12   33  42
3  200   14  201  16  202  43
4   17   18   19  20   35  44
5   90   91   92  93   94  45


In [111]:
del( df['E'] )
print(df)

     A    B    C   D   F
0   99    2    3   4  40
1  100  101  102   8  41
2    9   10   11  12  42
3  200   14  201  16  43
4   17   18   19  20  44
5   90   91   92  93  45


In [112]:
df = df.drop( 'F', axis=1 )
print( df )

     A    B    C   D
0   99    2    3   4
1  100  101  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20
5   90   91   92  93


In [113]:
df = df.drop( 5 )
print(df)

     A    B    C   D
0   99    2    3   4
1  100  101  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20


## Boolean Indexing

In [114]:
df = pd.DataFrame(
     [['kim', 20, '1111-2222'],
      ['lee', 30, '2222-1111'],
      ['park', 35, '3333-2222'],
      ['jung', 25, '3333-1111'],
      ['hong', 40, '1111-3333']], columns=[ 'name', 'age', 'tel']    
)
print( df )

   name  age        tel
0   kim   20  1111-2222
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111
4  hong   40  1111-3333


In [115]:
print( df.loc[3, 'name'] )

jung


In [116]:
print( df.loc[ df['age'] > 30, ['name', 'age' ]] )

   name  age
2  park   35
4  hong   40


In [118]:
print( df.loc[ df['name'] == 'kim', : ] )

  name  age        tel
0  kim   20  1111-2222


In [119]:
print( df.loc[ ( df['age']>20 ) & ( df['age']<40 ), 'name':'tel'] )

   name  age        tel
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111


In [120]:
print( df.loc[ [True, True, False, False, False], "name" ] )

0    kim
1    lee
Name: name, dtype: object


## 결측값 대체

In [121]:
df['address'] = [ '서울', np.nan, np.nan, '수원', None ]
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111     NaN
2  park   35  3333-2222     NaN
3  jung   25  3333-1111      수원
4  hong   40  1111-3333    None


In [122]:
print( df.loc[ df['address'] == np.nan, 'address' ]  )

Series([], Name: address, dtype: object)


In [123]:
print( df.loc[ df['address'] == None, 'address' ]  )

Series([], Name: address, dtype: object)


In [124]:
print( df.loc[ df['address'].isnull(), 'address' ] )


1     NaN
2     NaN
4    None
Name: address, dtype: object


In [125]:
df.loc[ df['address'].isnull(), 'address' ] = '서울'
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울


In [127]:
df.loc[ ::2, 'address' ] = '' 
print(df)

   name  age        tel address
0   kim   20  1111-2222        
1   lee   30  2222-1111      서울
2  park   35  3333-2222        
3  jung   25  3333-1111      수원
4  hong   40  1111-3333        


In [128]:
df.loc[ df['address'] == '', 'address' ] = '서울' 
print( df )

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울


In [129]:
df = pd.DataFrame(
     [['kim', 20, '1111-2222', '서울'],
      ['lee', 30, '2222-1111', np.nan ],
      ['park', 35, '3333-2222', '수원'],
      ['jung', 25, '3333-1111', np.nan],
      ['hong', 40, '1111-3333', np.nan]], columns=[ 'name', 'age', 'tel', 'address']    
)
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111     NaN
2  park   35  3333-2222      수원
3  jung   25  3333-1111     NaN
4  hong   40  1111-3333     NaN


In [130]:
df.loc[ 5, : ] = [ np.nan, np.nan, np.nan, np.nan ]
print(df)

   name   age        tel address
0   kim  20.0  1111-2222      서울
1   lee  30.0  2222-1111     NaN
2  park  35.0  3333-2222      수원
3  jung  25.0  3333-1111     NaN
4  hong  40.0  1111-3333     NaN
5   NaN   NaN        NaN     NaN


In [131]:
df['income'] = [ 300, np.nan, 400, 500, np.nan, 300 ]
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111     NaN     NaN
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111     NaN   500.0
4  hong  40.0  1111-3333     NaN     NaN
5   NaN   NaN        NaN     NaN   300.0


In [132]:
df.fillna( {'address' : '서울'}, inplace=True )
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울     NaN
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0
4  hong  40.0  1111-3333      서울     NaN
5   NaN   NaN        NaN      서울   300.0


In [133]:
df.fillna( {'income' : np.mean( df['income'] ) }, inplace=True )
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울   375.0
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0
4  hong  40.0  1111-3333      서울   375.0
5   NaN   NaN        NaN      서울   300.0


In [134]:
df.drop( [4, 5], inplace=True )
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울   375.0
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0


In [135]:
df.drop( ['address', 'income'], axis=1, inplace=True )
print(df)     

   name   age        tel
0   kim  20.0  1111-2222
1   lee  30.0  2222-1111
2  park  35.0  3333-2222
3  jung  25.0  3333-1111


In [137]:
# 전치행렬
print( df.transpose() )  

              0          1          2          3
name        kim        lee       park       jung
age        20.0       30.0       35.0       25.0
tel   1111-2222  2222-1111  3333-2222  3333-1111


# Pandas 함수

In [138]:
# Pandas 함수
df = pd.DataFrame( 
    [[ 'kim', 90, 80, 70 ],
     [ 'lee', 45, np.nan, 55 ],
     [ 'park', 76, 77, 83 ],
     [ 'hong', np.nan, np.nan, 77 ],
     [ 'kang', 35, 58, 52 ],
     [ 'jang', np.nan, np.nan, np.nan]], columns=[ 'name', 'kor', 'eng', 'mat' ]
)
print( df )


   name   kor   eng   mat
0   kim  90.0  80.0  70.0
1   lee  45.0   NaN  55.0
2  park  76.0  77.0  83.0
3  hong   NaN   NaN  77.0
4  kang  35.0  58.0  52.0
5  jang   NaN   NaN   NaN


In [139]:
print( df.count() )

name    6
kor     4
eng     3
mat     5
dtype: int64


In [140]:
print( df.count( axis=1 ) )

0    4
1    3
2    4
3    2
4    4
5    1
dtype: int64


In [141]:
print( df.min() )

name    hong
kor     35.0
eng     58.0
mat     52.0
dtype: object


In [142]:
print( df.loc[:, 'kor':'mat'].min( axis=1 ) )

0    70.0
1    45.0
2    76.0
3    77.0
4    35.0
5     NaN
dtype: float64


In [143]:
print( df.max() )

name    park
kor     90.0
eng     80.0
mat     83.0
dtype: object


In [144]:
print( df.loc[:, 'kor':'mat'].mean() )

kor    61.500000
eng    71.666667
mat    67.400000
dtype: float64


In [145]:
print( df.loc[:, 'kor':'mat'].mean( axis=1 ) )

0    80.000000
1    50.000000
2    78.666667
3    77.000000
4    48.333333
5          NaN
dtype: float64


In [146]:
print( df.sum() )

name    kimleeparkhongkangjang
kor                      246.0
eng                      215.0
mat                      337.0
dtype: object


In [147]:
print(df.loc[:, 'kor':'mat'].sum(axis=1))

0    240.0
1    100.0
2    236.0
3     77.0
4    145.0
5      0.0
dtype: float64


In [148]:
print(df.loc[:, 'kor':'mat'].median())

kor    60.5
eng    77.0
mat    70.0
dtype: float64


In [149]:
print(df.loc[:, 'kor':'mat'].cumsum())

     kor    eng    mat
0   90.0   80.0   70.0
1  135.0    NaN  125.0
2  211.0  157.0  208.0
3    NaN    NaN  285.0
4  246.0  215.0  337.0
5    NaN    NaN    NaN


In [150]:
print(df.loc[:, 'kor':'mat'].cumprod())

          kor       eng           mat
0        90.0      80.0  7.000000e+01
1      4050.0       NaN  3.850000e+03
2    307800.0    6160.0  3.195500e+05
3         NaN       NaN  2.460535e+07
4  10773000.0  357280.0  1.279478e+09
5         NaN       NaN           NaN


In [151]:
print(df.idxmax())

name    2
kor     0
eng     0
mat     2
dtype: int64


In [152]:
print(df.idxmin())

name    3
kor     4
eng     4
mat     4
dtype: int64


In [153]:
print(df.loc[:,'kor':'mat'].var())

kor    665.666667
eng    142.333333
mat    183.300000
dtype: float64


In [154]:
print(df.loc[:,'kor':'mat'].std())

kor    25.800517
eng    11.930353
mat    13.538833
dtype: float64


In [155]:
df['tot'] = df.loc[:,'kor':'mat'].sum(axis=1)
print(df)

   name   kor   eng   mat    tot
0   kim  90.0  80.0  70.0  240.0
1   lee  45.0   NaN  55.0  100.0
2  park  76.0  77.0  83.0  236.0
3  hong   NaN   NaN  77.0   77.0
4  kang  35.0  58.0  52.0  145.0
5  jang   NaN   NaN   NaN    0.0


In [157]:
df['avg'] = df.loc[:,'kor':'mat'].mean(axis=1)
print(df)

   name   kor   eng   mat    tot        avg
0   kim  90.0  80.0  70.0  240.0  80.000000
1   lee  45.0   NaN  55.0  100.0  50.000000
2  park  76.0  77.0  83.0  236.0  78.666667
3  hong   NaN   NaN  77.0   77.0  77.000000
4  kang  35.0  58.0  52.0  145.0  48.333333
5  jang   NaN   NaN   NaN    0.0        NaN


In [159]:
print(df['kor'].corr(df['eng']))
#1 : 양의 상관관계, -1 : 음의 상관관계, 0 : 상관관계가 낮다

0.9926458576614517
